### ISSUE TITLE
Spike: Explore ways to scale our GitHub data collection

### ISSUE THREAD

**Issue by hemajv** [oss-aspen/Rappel#187]
Currently, we have been relying on fetching a known number of GitHub repositories from the Augur database for our graphical  analysis work. However, in the future we would like to apply our graphical techniques to a much wider (unknown) set of relevant repositories that exist in GitHub. For this, we will need to explore different ways to scale our data collection process such as leveraging GitHub APIs and their functionalities.

**Comment by oindrillac** [comment]
The proposed ways we have considered to extend our list of Github projects are:

- Using the Github API to scan through OSS projects & filter by org level projects, forks, stars
- Project dependencies using https://www.stackaid.us/ and https://thanks.dev/home 
- Get list of contributed projects from interesting user groups using the Github API

**Comment by oindrillac** [comment]
Explore https://docs.github.com/en/graphql to scan through & query repos on Github

**Comment by erikerlandson** [comment]
A couple proposed filters that will hopefully allow new github repos to be queried in a small enough number to regularly analyze to identify "interesting" new repos to track via Aspen:

- select repos with >= `k` forks, where `k > 0` but exact number is experimentally determined. Generally `k` should be large enough to filter out at least 90% of repos but not larger than necessary. (90% is also a parameter to be determined experimentally)
- since the goal is to identify interesting _new_ projects, we can probably ignore any repo that is older than `x` months, where `x` is experimentally determined but probably something like 6 months.  Initial searches might go back a little farther until a regular search workflow is established.
- possibly also select repos with a minimum of other activity (prs, issues, commits, etc).  However, number of forks may turn out to be a sufficient surrogate for activity.

**Comment by oindrillac** [comment]
Fyi - @JamesKunstle @cdolfi mentioned that Augur has been building on functionality to go from user id to list of projects to they have contributed to. This will be very helpful in expanding our initial list of projects that we include into Augur and scale our data collection.

**Comment by hemajv** [comment]
Looked into https://docs.github.com/en/graphql and https://docs.sourcegraph.com/ for scaling our data collection.
Some observations based on my initial research:

- **GraphQL** - has an Explorer UI to test and run queries. A nice way to learn and test your queries. I was able to stitch together a query to pull all **public, non-forked repositories and the first n issues, PRs** in each of the repositories. However, I was unable to fetch the contributor information as its restricted based on authentication tokens and need to look into if specific privileges are needed for this.

- **Sourcegraph** - tool that leverages GitHub GraphQL to make it easy for developer to search for code across GitHub repositories. Although its primarily used for code search, we can modify our queries to filter for public GitHub repositories. Still exploring queries for fetching issue, PRs and contributor information.

One thing to keep in mind while using both the tools are the API request limitations. Although there are limits on the number of queries we can make per hour, we can still use it as a first pass for collecting our initial repo set.

**Comment by JamesKunstle** [comment]
@oindrillac @hemajv Should this be 'In Progress' at this stage, or should it be closed / backlogged?

**Comment by oindrillac** [comment]
This was a spike and looks complete. I think we can close this out.
