### ISSUE TITLE
Bug: count distinct commits

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#192]
The commits table has repeated commit IDs because the table tracks all of the changes for each file in a commit. Make sure you're only counting the distinct commit ID's created per individual when you're trying to figure out the core contributors.

**Comment by JamesKunstle** [comment]
also order issues by recency descending so that we're getting the 100000 most recent issues rather than random.

**Comment by mariashev** [comment]
_RE: The commits table has repeated commit IDs because the table tracks all of the changes for each file in a commit. Make sure you're only counting the distinct commit ID's created per individual when you're trying to figure out the core contributors._

Solution: COUNT(DISTINCT c.cmt_commit_hash) as num_commits

Notebook: https://colab.research.google.com/drive/1LWaNAHcIYl_aRCdqGDhklJ39aMUaaByZ?usp=sharing#scrollTo=a5o8HGOoDl7r
